### ISSUE TITLE
Some feedback and questions

### ISSUE THREAD

**Issue by kaphula** [Pyrdacor/freeserf.net#101]
Hello,

Good job on the port! I could not get the Linux build working on 64-bit Manjaro so I ran the Windows build through WINE. I did some testing and here's my thoughts so far.

**Improvements:**

Cursor position should be locked when scrolling is performed. Otherwise the cursor can reach side of the window and interrupt the scrolling. This is is the way it is in the original game.

 **Issues:**

Fast clicking for buildings and roads is not working. Despite turning on the settings from options. Double clicking on the map should invoke construction menu, create flag or start road building depending on what was clicked.

Checking for all of available building slots on the map (MB2 + MB1) opens the construction menu. Holding MB2 and then clicking MB1 (many times) on the GUI build icon should not open the construction menu but instead toggle between showing the possible buildings slots on the map.

The game does not show all of the possible building places on the map. Clicking on spots containing something else than a yellow icon of a building can reveal new hidden house or castle icons. I am not sure if this was the same in the original game but it is kind of odd. See video.

**Questions:**

What's the current situation with changing the simulation speed? I could not find a way to change it. I think this is one the most important improvements to have.

**EDIT:**

I'd also be interested in experimenting with these changes myself using MonoDevelop (if possible), but I am having hard time getting the project set up. I have installed bunch of dotnet SDKs but for some reason the project just is not happy.

Here are my installed SDKs on MonoDevelop:

![image](https://user-images.githubusercontent.com/36015558/80871805-b3ff2200-8cb6-11ea-8be8-60aeed3438ce.png)

And here are the error messages I get from trying to update NuGet packages:

```
estoring packages for .NETCoreApp,Version=v3.1...
Resolving conflicts for .NETCoreApp,Version=v3.1...
Checking compatibility of packages on .NETCoreApp,Version=v3.1.
Checking compatibility for FreeserfNet 1.0.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for glfw 3.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for Silk.NET.Core 1.2.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Silk.NET.GLFW 1.2.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Silk.NET.Input 1.2.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Silk.NET.Input.Common 1.2.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Silk.NET.Input.Desktop 1.2.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Silk.NET.OpenGL 1.2.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Silk.NET.Windowing 1.2.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Silk.NET.Windowing.Common 1.2.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Silk.NET.Windowing.Desktop 1.2.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Freeserf.Audio 1.0.0 with .NETCoreApp,Version=v3.1.
NU1201: Project Freeserf.Audio is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Project Freeserf.Audio supports: netstandard2.1 (.NETStandard,Version=v2.1)
Checking compatibility for Freeserf.Core 1.0.0 with .NETCoreApp,Version=v3.1.
NU1201: Project Freeserf.Core is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Project Freeserf.Core supports: netstandard2.1 (.NETStandard,Version=v2.1)
Checking compatibility for Freeserf.Network 1.0.0 with .NETCoreApp,Version=v3.1.
NU1201: Project Freeserf.Network is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Project Freeserf.Network supports: netstandard2.1 (.NETStandard,Version=v2.1)
Checking compatibility for Freeserf.Renderer 1.0.0 with .NETCoreApp,Version=v3.1.
NU1201: Project Freeserf.Renderer is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Project Freeserf.Renderer supports: netstandard2.1 (.NETStandard,Version=v2.1)
Checking compatibility for Silk.NET.Window 1.0.0 with .NETCoreApp,Version=v3.1.
NU1201: Project Silk.NET.Window is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Project Silk.NET.Window supports: netstandard2.1 (.NETStandard,Version=v2.1)
Checking compatibility for Microsoft.CSharp 4.7.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Memory 4.5.3 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Numerics.Vectors 4.5.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Reflection.Emit 4.7.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Reflection.Emit.ILGeneration 4.7.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime.CompilerServices.Unsafe 4.7.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Ultz.SuperInvoke 1.0.4 with .NETCoreApp,Version=v3.1.
Checking compatibility for Ultz.Native.GLFW 3.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for Ultz.SuperInvoke.Loader 1.0.4 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.DependencyModel 3.1.1 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.DotNet.PlatformAbstractions 3.1.1 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Text.Json 4.7.0 with .NETCoreApp,Version=v3.1.
Incompatible projects: 5
Package restore failed. Rolling back package changes for 'FreeserfNet'.
``` 
**EDIT 2**
So I got the game compiled and running on Linux using JetBrains' Rider

**Comment by Pyrdacor** [comment]
Hey thanks for your feedback. I am very limited at the moment but I will look into it as soon as possible.

Game speed can be changed by + and -. You can also pause/resume with P.

**Comment by Pyrdacor** [comment]
About your problems with MonoDevelop. I only build it with Vscode + dotnet cli on Linux so I don't know much about MonoDevelop. But maybe you need the NETStandard 2.1 dependency in addition. I remember there were issues with NETStandard in the past in general so maybe you might be lucky by searching for your problem on SO or the like.

**Comment by Pyrdacor** [comment]
About the mentioned issues. Please create new smaller issues for each of them so we can track and fix them. ;)

**Comment by kaphula** [comment]
Alright, I will separate the issues. Just a quick question: Can you debug the project normally with vscode, breakpoints working and all? I am having trouble getting debugging to work with vscode.

**Comment by Pyrdacor** [comment]
I have done the most of debugging on Windows with Visual Studio but if I remember correctly it also worked with vscode. Maybe you need some additional plugins? What exactly doesn't work? Be aware that you use the correct configuration. In contrast to normal ones (Release/Debug) there are LinuxDebug, etc. I guess vscode is not good with special configurations. But maybe this causes your issues.

**Comment by kaphula** [comment]
It seems that vscodium, an open source version of vscode that I am using, cannot be used with the official Microsoft debugging tools / extensions. There seems to exist an [alternative open source debugger](https://github.com/Samsung/netcoredbg), so I will check out if I can get the debugging running with that.

**Comment by Pyrdacor** [comment]
@kaphula I see you run Freeserf on linux. I need some testing for linux distributions to fix bugs if necessary. There is a tracking issue for testing linux distributions here: https://github.com/Pyrdacor/freeserf.net/issues/87

Maybe you can help with that. Thanks.
