### ISSUE TITLE
Map size 9 is not stable

### ISSUE THREAD

**Issue by kaphula** [Pyrdacor/freeserf.net#103]
Generating a world with map size 9 has issues. Flags are not being rendered at all and the game crashes randomly when camera zoom is performed.

**Comment by Pyrdacor** [comment]
This is indeed strange. With map size 8 everything is fine. Even the AI will burn down all their planned buildings immediately with map size 9. Kinda funny bug. :D Will have a look at it.

**Comment by Pyrdacor** [comment]
Ok I found it. The flag position was cast to a word (16 bit uint) inside the setter, so for larger positions the position was wrong. I guess it was a copy&paste mistake when I implemented game state serialization. Now everything should work fine even with map size 9.
