### ISSUE TITLE
Fast building is not working

### ISSUE THREAD

**Issue by kaphula** [Pyrdacor/freeserf.net#104]
The following fast building features are not working as they should:
- Consecutively clicking twice on the same flag should invoke road building.
- Consecutively clicking twice on the same building icon should invoke the building construction menu.

**Comment by Pyrdacor** [comment]
I am not familiar with fast building but following your explanation I implemented it the way I thought it would be plausible. Can you check with latest master commit if it is ok now? Thanks

**Comment by Pyrdacor** [comment]
Note: I also added building a castle by clicking a second time on the build icon for it. Don't know if this is useful/desirable.

**Comment by kaphula** [comment]
Fast building seems to be working correctly now. Nice one! 

There's only one minor quirk I found. Trying to fast build a flag opens the building construction menu, which is pointless really since you can only choose to build a flag from within the menu. The flag should be built instantly in this kind of situation (see screenshot).
![image](https://user-images.githubusercontent.com/36015558/81348837-83a8f080-90c7-11ea-9342-8ff48263e57f.png)

**Comment by Pyrdacor** [comment]
Should work now as expected.
