### ISSUE TITLE
Feature request: Have an option to change the inverted joystick scrolling.

### ISSUE THREAD

**Issue by GraionDilach** [Pyrdacor/freeserf.net#109]
Pretty sure SerfCity wasn't like this. I know some games have this kind of scrolling but it feels weird if one comes from games not having it.

**Comment by Pyrdacor** [comment]
You already have this option inside the option menu.

**Comment by GraionDilach** [comment]
Ooops, sorry, I didn't notice that the options menu have a pages variant and this can only be changed ingame and not while you're in the main menu screen.

**Comment by Pyrdacor** [comment]
Actually it was also changeable in the main menu but when I added some more map scroll options I decided to show them all only ingame. Maybe I change that so the ingame and main option menu match.

**Comment by Pyrdacor** [comment]
FYI: The options are now also available in the main menu. The associated release will come later though.
