### ISSUE TITLE
graphics for game statistics not shown correctly

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#11]
[Build v1.6_statistical_graphics.zip](https://github.com/Pyrdacor/freeserf.net/files/2957804/Build.v1.6_statistical_graphics.zip)
(the first click yielded even less information, after going back and clicking that statistic section again it yields above info)

**Comment by Pyrdacor** [comment]
Should be fixed in v1.7.

**Comment by Pyrdacor** [comment]
I found the true reason and fixed it in pathc 1.9.2.
