### ISSUE TITLE
Fast building a mine creates a flag

### ISSUE THREAD

**Issue by kaphula** [Pyrdacor/freeserf.net#110]
As the title says. I attempted to fix this but it was not that simple (https://github.com/kaphula/freeserf.net/commit/fd0a7bf8b52e065cd2213c5992c4eff53ae80500), you can take a look. With my changes the fast building of flags fails unless the flag is being built on desert or near water.

**Comment by Pyrdacor** [comment]
This is because `CanBuildSmall` and `CanBuildMine` only check the terrain types. Your logic is ok as long as you don't consider blocking roads, buildings or flags. You were on the right track. I fixed it in my latest commit. Thanks for your efforts.
