### ISSUE TITLE
Selecting my own building results with a blocked two-arrow cursor instead of the location cursor.

### ISSUE THREAD

**Issue by GraionDilach** [Pyrdacor/freeserf.net#116]
Inconsistency with the original. This was useful in Settlers 1 to see if a spot was elevated from hut area to castle area because of a removed blocker (say, rocks).

**Comment by Pyrdacor** [comment]
I don't get what you mean. Can you please provide some Screenshots?

**Comment by GraionDilach** [comment]
Settlers:

![image](https://user-images.githubusercontent.com/1136302/97078039-4e4a7d80-15e9-11eb-9a28-f03ae3af14d2.png)

Freeserf.Net

![image](https://user-images.githubusercontent.com/1136302/97078097-b4370500-15e9-11eb-85ac-f3a561afb480.png)

**Comment by Pyrdacor** [comment]
Ah ok I understand now.

**Comment by Pyrdacor** [comment]
Fixed it in code. Next release will contain the change.

**Comment by Pyrdacor** [comment]
Should be fixed in v2.0.8.

**Comment by GraionDilach** [comment]
Confirmed.
