### ISSUE TITLE
Autojoining a new flag to a road turns a section carrierless.

### ISSUE THREAD

**Issue by GraionDilach** [Pyrdacor/freeserf.net#117]
Expected behaviour:

When the flag's autojoin-to-proximity-road feature is used and the carrier remains on the road then the carrier is assigned to this new road segment.

Actual behaviour:

When the flag's autojoin-to-proximity-road feature is used and the carrier remains on the road then the carrier returns to the nearest stock and the road remains unoccupied until it's cleared and remade.

**Comment by Pyrdacor** [comment]
I implemented it partially but it needs a bit more adjustment. When I'm done I will release a new version with all the fixes.

**Comment by Pyrdacor** [comment]
Should be fixed in v2.0.8.

**Comment by GraionDilach** [comment]
Confirmed.

**Comment by tlongstretch** [comment]
this was a bug in original Freeserf, when splitting a road it only checked of one of the two directions to handle the transporter, so 50% of the time it results in loss of transporter.  I assume Pyrdacor applied same fix that I did... check both road dirs and fix both
