### ISSUE TITLE
Knights fighting forever then it freezes

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#119]
Northwest of my castle one of the red knights met one of my knights and now they fight forever, blocking all traffic. Game freezes few seconds after loading the third (last) game-save.
[3_savegames.zip](https://github.com/Pyrdacor/freeserf.net/files/5467790/3_savegames.zip)

**Comment by Pyrdacor** [comment]
I found the issue and fixed it in 2.1.0. Unfortunately the changes will not allow the old savegames to work anymore at least those which had knights fighting on free terrain. Other savegames will still work.

I fixed your savegame manually so it will work and the fight finishes. See attachment. Please test it. :)

[b208m3ai1gam1s3.zip](https://github.com/Pyrdacor/freeserf.net/files/5652520/b208m3ai1gam1s3.zip)
