### ISSUE TITLE
pregame RGB level not clickable

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#12]
they are all set to zero for all players: 
![RGB_level_not_clickable](https://user-images.githubusercontent.com/48333665/54304280-2c7abf00-459b-11e9-8a7c-eddf6d296c39.PNG)

**Comment by JSettler** [comment]
apparently they -are- clickable but the color bars are never shown, so it's a minor issue

**Comment by Pyrdacor** [comment]
I fixed it. Try to restart the game. A patch announcement should pop up. If you accept the patch, the game will be updated to version 1.7.1. Then the colored bars should be visible again.

Let me now if this worked for you.

**Comment by JSettler** [comment]
yes! thank you (the patcher is very useful)

but another graphical issue is that the lower ingame-menu often is covered by blue or red color to the point that it's barely visible (and sometimes i couldn't even click it)

**Comment by Pyrdacor** [comment]
I know this bug. I had it a few times, adjusted code and thought it was gone. But it seems that it is still there. I can't really find out why this happens but I will look into it soon.

**Comment by Pyrdacor** [comment]
It should be fixed.

**Comment by Pyrdacor** [comment]
About the lower ingame-menu. I worked on the renderer and the interface code. Hopefully this is also fixed now.
