### ISSUE TITLE
[Linux] crashes when started on Ubuntu 20.04

### ISSUE THREAD

**Issue by senneschall** [Pyrdacor/freeserf.net#121]
The game just crashes with the single line
`*** stack smashing detected ***: terminated`

I'd like to give you more details, but it crashes before it even begins any logging or any form of output.
libgdiplus is installed, ldd shows that any other dependecy is fulfilled. The SPA*.PA was copied over.

**Comment by Pyrdacor** [comment]
Thanks for reporting. This error is hard to track down. As this only happens for you, maybe it's something with your drivers or some error in the OpenGL libs. It could be anything but if I had to bet I would say it's hardware or setup related.

Maybe you can create a config manually and specify the correct resolution before start. If this is graphic related this might help. Another option would be to turn music and sound off. Also possible via config.

More info about it here: https://github.com/Pyrdacor/freeserf.net/blob/master/Configuration.md

Maybe first try this out and tell me how it went.

**Comment by Pyrdacor** [comment]
You can also try command line arguments to set a specific resolution and set the log level to "Info":

`./FreeserfNet -r 1280x960 -d 2 -c`

**Comment by senneschall** [comment]
I tried both:
1) created the ~/.local/share/freeserf/user.cfg and copied the content from the Configuration page
2) tried all of those commandline parameters available in different combinations

It's all the same, the binary crashes immediately, even before it even logs anything:
`./FreeserfNet -r 1920x960 -d 2 -c`
`*** stack smashing detected ***: terminated`

A `ldd FreeserfNet` shows all dependencies resolved, so no problem there. My drivers are still the default drivers from the ubuntu 20.04.2:
`glxinfo`
`OpenGL vendor string: X.Org`
`OpenGL renderer string: AMD Radeon (TM) RX 460 Graphics (POLARIS11, DRM 3.35.0, 5.4.0-70-generic, LLVM 11.0.0)`
`OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.6`
`OpenGL core profile shading language version string: 4.60`

I'd really like to help you find the error, but I don't know how to debug this.

**Comment by Pyrdacor** [comment]
I don't know what your background is but the easiest solution would be to compile the code yourself and debug.

But it is not that easy on Linux. You could download the NET Core 3.1 SDK and run a `dotnet build FreeserfNet.sln -c Debug`. This would at least build the debug information. Maybe this already helps getting a different error message.

**Comment by senneschall** [comment]
I'll give it a try as soon as I find the time.

**Comment by senneschall** [comment]
After some failed trys and learning some knowledge about linux and .net, I actually ended with the MS dotnet-sdk-3.1 you suggested in the first place. But still no success:

>$dotnet build FreeserfNet.sln -c Debug
>Microsoft (R)-Build-Engine, Version 16.7.2+b60ddb6f4 für .NET
>Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
>
>  Wiederherzustellende Projekte werden ermittelt...
>  Alle Projekte sind für die Wiederherstellung auf dem neuesten Stand.
>  Silk.NET.Window -> /home/user/src/freeserf.net-2.1.0/Silk.NET.Window/bin/Debug/netstandard2.1/Silk.NET.Window.dll
>  Freeserf.Core -> /home/user/src/freeserf.net-2.1.0/Freeserf.Core/bin/Debug/netstandard2.1/Freeserf.Core.dll
>  Freeserf.Renderer -> /home/user/src/freeserf.net-2.1.0/Freeserf.Renderer/bin/Debug/netstandard2.1/Freeserf.Renderer.dll
>  Freeserf.Test -> /home/user/src/freeserf.net-2.1.0/Freeserf.Test/bin/Debug/netcoreapp3.1/Freeserf.Test.dll
>  Freeserf.Network -> /home/user/src/freeserf.net-2.1.0/Freeserf.Network/bin/Debug/netstandard2.1/Freeserf.Network.dll
>  Freeserf.Audio -> /home/user/src/freeserf.net-2.1.0/Freeserf.Audio/bin/Debug/netstandard2.1/Freeserf.Audio.dll
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018: Unerwarteter Fehler bei der CreateAppHost-Aufgabe. [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018: System.IO.IOException: Invalid argument [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 requestedOffset, Int64 requestedSize) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(Int64 offset, Int64 size, MemoryMappedFileAccess access) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__RewriteAppHost|0() [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>
>Fehler beim Buildvorgang.
>
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018: Unerwarteter Fehler bei der CreateAppHost-Aufgabe. [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018: System.IO.IOException: Invalid argument [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 requestedOffset, Int64 requestedSize) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(Int64 offset, Int64 size, MemoryMappedFileAccess access) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__RewriteAppHost|0() [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>/usr/share/dotnet/sdk/3.1.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/user/src/freeserf.net-2.1.0/FreeserfNet/FreeserfNet.csproj]
>    0 Warnung(en)
>    1 Fehler
>
>Verstrichene Zeit 00:01:00.55
>

I guess I'll stop now, this goes way too deep for me. Maybe I'll just try wine.
Anyways, good luck with the project :)

**Comment by Pyrdacor** [comment]
I'm sorry that it did not go well. Maybe I can provide some debug assembly in a few days.

Thanks for your support! :-)

**Comment by Pa9an** [comment]
Not sure if this fits in here:
I am trying to run on 64bit Linux Mint 20 here (Ubuntu-based).
When starting, it's saying right away: "bash: ./FreeserfNet: Datei oder Verzeichnis nicht gefunden".
From what I understand is that this kind of error comes up when trying to run a 32bit program on 64bit architecture (when the appropriate x386 libs are not installed).

So, is the Linux version compiled only for 32bit?
Any chance to provide a 64bit version also?
(Ambermoon.Net in 64bit works nicely)

**Comment by Pyrdacor** [comment]
It's the other way around. The Linux executable is compiled for 64bit. Can you look into the log file which should be created if there is more information?

**Comment by Pa9an** [comment]
Unfortunately the program doesn't even get as far as creating a log. It won't even start properly...like it cannot be executed as a program "exe". Not even Linux gives me a log of anything... :-/
In the program code I found some "snap" reference (/usr/lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gn), does this have anything to do with relying on the Ubuntu snap format (and might have an impact on compiling)?

**Comment by Pyrdacor** [comment]
Freeserf.net and Ambermoon.net use the same build pipeline and window system. The only difference is the version of Silk.net. I will update the version soon. Other than set I don't see any reason why it should not be a real executable. I guess the error comes from a missing dependency. This can also have this error message afaik. Maybe more recent versions of Silk.net can handle dependencies better or have some built-in references on Linux.

I think we should try a newer version.

**Comment by senneschall** [comment]
Update: upgrading to Ubuntu 22.04 fixed the crash for me.
So I guess I can close this issue.
