### ISSUE TITLE
savegame could not be loaded

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#13]
"Error: [savegame] Failed to load save game: The specified key was not specified in the dictionary."
(second part translated with google)
[B17M3DEMO1AI4.zip](https://github.com/Pyrdacor/freeserf.net/files/2963143/B17M3DEMO1AI4.zip)
saved after running the demo for minutes (max speed)

**Comment by JSettler** [comment]
now i loaded a new savegame and it said "successfully loaded" but then it froze and windows gave an AppCrash log:
----------------------
Problem signature:
   Problem Event Name: clr20r3
   Issue signature 01: Freeserf.net.exe
   Issue signature 02: 1.7.1.0
   Problem signature 03: e7ed953f
   Issue Signature 04: mscorlib
   Issue Signature 05: 4.7.3324.0
   Issue signature 06: 5c09b7d7
   Issue Signature 07: 334
   Issue Signature 08:10
   Issue signature 09: System.ArgumentException
   OS Version: 6.1.7601.2.1.0.768.3
   Locale ID: 1031
   Additional information 1: 0a9e
   Additional information 2: 0a9e372d3b4ad19135b953a78882e789
   Additional information 3: 0a9e
   Additional Information 4: 0a9e372d3b4ad19135b953a78882e789
----------------------
with that savegame: 
[B171M3DEMO-SAVETEST1.zip](https://github.com/Pyrdacor/freeserf.net/files/2964088/B171M3DEMO-SAVETEST1.zip)

**Comment by JSettler** [comment]
(oops.. i dont know why the font became now that big :/ )

**Comment by Pyrdacor** [comment]
First error should be just fixed in patch 1.7.2.

**Comment by Pyrdacor** [comment]
About second error: It doesn't crash for me. Maybe the patch solved this as well? Please try again with patch 1.7.2. Does it always crash?

**Comment by JSettler** [comment]
i loaded it with 1.7.2 that worked, but then (after a ~1 minute speedrun & saving) it couldnt reload with that log: "Error: [savegame] Failed to load save game: Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt."

**Comment by JSettler** [comment]
(in english: ~"..an element with the same key had already been added.")

**Comment by JSettler** [comment]
..but that was the old savegame, now i make a new one with v1.7.2 and try that..

**Comment by JSettler** [comment]
tested 1.7.2 and it gave the same above error in the log.
with that savegame: 
[B172-DEMO1-SAVE1.zip](https://github.com/Pyrdacor/freeserf.net/files/2964147/B172-DEMO1-SAVE1.zip)

**Comment by Pyrdacor** [comment]
Ok I'll look at it tomorrow.

P.S.: Keine Sorge. Ich kann auch die deutschen Fehlertexte lesen. ;D Aber ist schon besser hier bei Englisch zu bleiben, falls andere auch auf die gleichen Fehler stoßen. :)

**Comment by JSettler** [comment]
ok cool :) are you at xing? there is a guy with your exact name (which is given in the sourcecode)
[PS: ich kann auch deutsch]

**Comment by JSettler** [comment]
maybe this helps in debugging: i managed to make a savegame before it became unloadable later:
[B172-M3-GAME1-SAVE1.zip](https://github.com/Pyrdacor/freeserf.net/files/2964276/B172-M3-GAME1-SAVE1.zip)
then i continued some minutes and saved that one (which gave above error after a load-attempt):
[B172-M3-GAME1-SAVE2.zip](https://github.com/Pyrdacor/freeserf.net/files/2964279/B172-M3-GAME1-SAVE2.zip)

**Comment by Pyrdacor** [comment]
Should be fixed in patch 1.7.3.

**Comment by JSettler** [comment]
Now it happened while saving (a new game under 1.7.3): i got the error "The given [or: specified] key was not specified in the dictionary" then it froze and i couldn't even click on 'details' to open the windows details of it (it was the standard window for unhandled exceptions with a white X on a red disc)
(The game was a 4-AI demo speedrun of 1-2 minutes on a size-3 map)

**Comment by JSettler** [comment]
i just tested a second game (with 2 AIs and the red bar[=serf growth] at less than 25%, all other bars at max) on a size3-map and ran that in speedrun mode for a very short time then slowed, stopped and saved. That worked. Reload worked, too.
I'll continue it to see if it ceases to save in a later stage.

**Comment by Pyrdacor** [comment]
You mean the freeze came while trying to save the game?

**Comment by JSettler** [comment]
yes, exactly
it was a very complex game with 4 maxed AIs(the highest-level AI-personalities) with a long speedrun on a compact map (3)

**Comment by JSettler** [comment]
(and hi!)

**Comment by JSettler** [comment]
(the game window itself freezes but windows gave that crash-report so i guess it's classifyable as a "normal crash")

**Comment by Pyrdacor** [comment]
Thank you for the error message. This bug should now be fixed easily. But I won't have the time today. I will fix it tomorrow and also ensure that such crashes will result in a normal error message with the possibility to see the reason and save the current game (if possible).

**Comment by JSettler** [comment]
(in the other thread [about start-freezing] i already mentioned it) v1.8.1 failed to load a long speedrun of a 4-AI-demogame with "Error: [savegame] Failed to load save game: The value for an Int32 was too big or too small. "
[B181-DEMO2-SAVE1.zip](https://github.com/Pyrdacor/freeserf.net/files/2973272/B181-DEMO2-SAVE1.zip)

**Comment by JSettler** [comment]
how can i get the backtrace-info-window?

**Comment by JSettler** [comment]
Maybe the load-error has something to do with the fact that in this game two of the AI had traffic-clogs in their settlement and couldn't make progress at all (it looked as if 2 serfs tried to pass another, but instead waiting forever, standing at the opposite ends of the road without moving and behind them a growing queue of serfs clogging up the street-network)

**Comment by JSettler** [comment]
another example for a game where the first save can be loaded but a later second save can't be loaded anymore resulting in the log "Error: [savegame] Failed to load save game: The value for an Int32 was too big or too small."
[B181-3AI-DEMO.zip](https://github.com/Pyrdacor/freeserf.net/files/2974108/B181-3AI-DEMO.zip)
(in a third speedrun i tested only 2 AIs in a demo, that one is loadable/saveable flawlessly so far)

**Comment by Pyrdacor** [comment]
Yes this bug should be fixed in patch 1.8.2.

**Comment by JSettler** [comment]
Indeed, good job.

**Comment by Pyrdacor** [comment]
The bug with the color should hopefully be gone. After bugfixing I also want to finish and tune AI logic. Moreover I have a ToDo list as well. E.g. the elevator of mines is not drawn correctly yet. It will take a while to RC. But thanks to your help it makes good progress. Stability is very important.
