### ISSUE TITLE
some AIs seem to have problems in an early game phase sometimes..

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#14]
in that same savegame (which can't be loaded), the magenta AI(No.7 = 'Count Aldaba',) stopped to deliver material to its construction sites even with enough resources and priorities correctly set (and enough carriers present); the yellow AI(No.8 = 'King Rolph VI') had problems too: it stopped creating new buildings.
[Edit: This is only a minor issue, in my opinion, because the other AIs worked flawlessly in that game.]

**Comment by Pyrdacor** [comment]
AI behavior bugs are hard to track. Note that AI is not fully finished yet. Especially in later game the AI won't build some buildings as simply the logic and commands for them are missing.

If no materials are delivered with correct settings, this would be a bug in serf logic. They are even harder to track and I think there are still some of them. I fix some from time to time but as I said it is very hard to find them.

**Comment by Pyrdacor** [comment]
I found some issues that may stop an AI from doing anything anymore. I fixed it in patch 1.8.2. Could you test the mentioned savegame with the patch?

**Comment by JSettler** [comment]
ok, thats good. but the problem is that i've deleted all older savegames (prior to ~1.7.2 iirc) because i had not enough space in the save folder (it only shows ~11 files, if there are more they aren't shown in the load menu because there is no scroll-bar). But from now on i'll archive those older savegames in a different directory (outside the standard 'freeserf' dir)

**Comment by Pyrdacor** [comment]
You can also create a subdirectory in the save directory with the recent version. They won't appear in the game but also won't bother. Scrollbars are very helpful but there are no graphics for that in the original game data and I don't want to add additional graphics. Maybe I could use colored shapes instead but it didn't had prio yet.

**Comment by JSettler** [comment]
I made a new game on mapsize 5 vs 3 AI(maxed) where it happens again, that the AI stopped growing/building entirely, becoming static.
[B183-MAP5_game1-VS-3AI-SAVE1.zip](https://github.com/Pyrdacor/freeserf.net/files/2975482/B183-MAP5_game1-VS-3AI-SAVE1.zip)

**Comment by JSettler** [comment]
Now i tested with 1.9.1 on a size-3 map and it first looked the same but i let the speedrun continue and after ~1-2 minutes it began to teem with activity. Then i realized that the AI converted all of their serfs into knights (until all weapons were used up), and i gave it maximum start-resources (like in nearly all of my test-games) so that could also explain the seemingly staticness in other games, because the AI just hadn't enough non-military-serfs to grow its settlement. Wouldn't it be better to let the AI decide how high the recruitment factor should be, instead of making it 100%? (then it wouldn't be stunted in their beginning growth which is a handicap)

**Comment by Pyrdacor** [comment]
As mentioned in the other thread, this should be fixed with patch 1.9.2.
