### ISSUE TITLE
freeze(crash) right after starting

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#15]
log: "Error: [render] The object reference was not set to an object instance."
maybe a fluke
(i had to close it with taskmanager)
there was no error-window this time

**Comment by JSettler** [comment]
Now it happened while trying to switch the game mode (it was in the missions-mode while i clicked)

(windows gave an error window but i couldnt select it because freeserf.net covered it and was frozen, taskmanager-quitting closed that error-window too)

**Comment by JSettler** [comment]
i wonder why these errors happen now and not when i made the first savegames... its strange for me

**Comment by JSettler** [comment]
hm.. or i could reload v1.7.3 (or unpack my original downloaded archive) and use that..

**Comment by JSettler** [comment]
I think the key to start solving this issue is to get the error report from windows, the problem is that the frozen game-window covers it, my approach would be to forward the output to a file via cmd.exe with „>“ operator, is that possible with the current build?

**Comment by JSettler** [comment]
i researched and found the "Computer Administration" system app with its embedded Event Viewer, there is a section for protocols. In the help it's said that the analytic- and debug-logging has to be activated first, but i can't get that to work, i copied the command as said in the cmd.exe to activate it with "wevtutil sl wevt_log.txt /e:true"-command (like the Help advised) [in the subDir of freeserf-build173] and it gave that error: "Error reading configuration for "wevt_log.txt" log. The specified
  Channel was not found. Check the channel configuration.", this is starting to go over my head. This debug-logging facility could prove really useful, if we can configurate&activate it.

**Comment by JSettler** [comment]
(if you wish, i can give you these logs (they were made yesterday evening), but i guess they are probably related to the other issue which i already gave you an error-log for.)

**Comment by Pyrdacor** [comment]
Very strange. As you did not change anything I think at has to do with your file system. After the mission game mode there is the savegame load screen. My guess is, that the filename of a savegame has a bad character in it. Please ensure that all savegame filenames only contain letters and the minus sign. Another reason could be that freeserf could not access the directory for saved games.

Anyway the game should not crash that hard in any case. Can you try v1.8 and look if you get some error message?

If you find a savegame with a bad name, please let me know its original filename so I can reproduce and fix this issue.

**Comment by JSettler** [comment]
Ok, will check it later today(in ~8-9 hours) thanks for your hard work!

**Comment by JSettler** [comment]
tested 1.8.1:
it has the same problem: after clicking the 2nd time on mode button it freezes and i can't switch to any other window (alt/ctrl-tab/esc does nothing and clicking mouse only yields a 'ding'-sound), with crashhandling-window covered and only ctrl-alt-del works (and i had to close it with taskmanager).
Log says: "Error: [FrameTimer] The object reference was not set to an object instance."
The freeserf-save-folder contained only 2 subdirectories with names "other_savegames" and "build173_demo2" and no files at all (the folder access rights were not changed, all users have full access to the directory)

**Comment by JSettler** [comment]
can you message panzerchris and ask him if he has the same problem? (he is the third watcher of this project) or other people like tlongstretch or the surfer (whose name i forgot and who left shortly ago)

**Comment by JSettler** [comment]
if all attempts fail there is always the possibility to change to an easier to debug language like Blitzmax (which is free+opensource and can compile the same source for windows/linux/macos; it has a speed of 50%-70% of optimized C code and can be found at http://nitrologic.itch.io/blitzmax)
[the fourth watcher was named 'nskalski' or something similar, i just recalled]
(but i guess porting to a different language is (nearly?) out of the question here because of the amount of work already invested)

**Comment by JSettler** [comment]
i found a (strange) solution by pure luck:
if i let the game run in one of the first 2 modes (and quit back to menu) i can now select the other modes after the 2nd! yay! i can even load and save without error! that is unbelievable, i was on the brink of giving up, but this is a true work-around and we can now finally continue hunting bugs :-)

**Comment by Pyrdacor** [comment]
I already fixed the last one but I want to look at some other things before releasing the next patch.

Did your crash with the load screen appear again?

**Comment by JSettler** [comment]
Thanks for asking that. It motivated me to make a special test with both freeserf-folders:
the new folder (with only save files) caused no problems, but the old folder with 2 subdirectories caused the freeze-crash! the 2 subDirs were: "other_savegames" and "build173_demo2"
I'm happy now that the crash is 100% reproducable.

**Comment by Pyrdacor** [comment]
Thank you for your efforts. I could track the issue with your help. The problem was an empty savegame list. You must know that the savegames must be in directly inside the freeserf folder to get displayed. If there is no such folder or the folder does not contain any *.save files the bug would occur because then the selected savegame is null and this wasn't handled correctly. The reason why it crashed with subdirs was only that the freeserf folder itself did not contain save-files. I just tested it. Subdirs are ok as long as there were save-files inside the root dir. I will release a patch in the next minutes.

**Comment by Pyrdacor** [comment]
Ok patch 1.8.2 is out and should fix the issues.
