### ISSUE TITLE
update to .net sdk?

### ISSUE THREAD

**Issue by njskalski** [Pyrdacor/freeserf.net#159]
Hi,

I wanted to play around with the code (I want to make an AI opponent as an exercise) but I am not super proficient in .net and I was surprised to learn that you can't download the old .net sdk from Microsoft any more.

So we have two options:
1) update to one of more modern SDKs
2) make sure Mono works

Can you help me with either of the options?

**Comment by Pyrdacor** [comment]
Sure. Shouldn't be too hard.

**Comment by Pyrdacor** [comment]
I updated the project to use .NET7. Tell me if it works.

**Comment by njskalski** [comment]
It compiles, but now System.Common.Drawing is not supported. I tried to replace it with SkiaSharp, but I couldn't find equivalent for 32bitArgb setup, so I didn't know how to modify the loading functions that throw an exception now.

**Comment by Pyrdacor** [comment]
Wasn't aware of this as I am on Windows currently. I will try to remove the dependency this week hopefully.

**Comment by Pyrdacor** [comment]
Ok I removed the dependency and used ImageSharp to load the images. This even eases the image loading. Should hopefully compile and run on Linux now.

**Comment by njskalski** [comment]
yes, it works! Now I have to figure out sound and speed, but I can probably take it from here.
