### ISSUE TITLE
a minor issue: sometimes a 'shadow' of an earlier game was shown in a second game

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#16]
i recalled, that v1.7 sometimes showed some relics of former games when going back to menu and starting a new game, then one could see old settlement borders while scrolling the view. the real borders stuck in the landscape while the former 'shadow' borders moved in it (while moving the view), thus showing two overlapping settlement-borders. But in v1.8 i didnt see that yet, maybe it got fixed as a side-effect of other bugfixes.
In v1.7 the work-around was to restart freeserf.net (sorry that i forgot to report it earlier, i thought it was not important compared to the other issues)

**Comment by Pyrdacor** [comment]
Hm I didn't change anything related to it so I leave this open. Maybe it occurs again.

**Comment by Pyrdacor** [comment]
I know changed how the renderer reuses and therefore deletes unused render data. This might fix this issue.
