### ISSUE TITLE
AI behaves very different on the largest mapsize (9)

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#17]
It seems to only build a handful buildings in contrast to smaller mapsizes (i tested til size 5, were it expands normally).
And it takes a very long time on 9 to even choose a place for its castles.
[B183-M9-4AI-DEMO1-SAVE1.zip](https://github.com/Pyrdacor/freeserf.net/files/2974568/B183-M9-4AI-DEMO1-SAVE1.zip)
(i'll test on size 7 later)

Edit:
It seems the bigger the map is the more it hampers the progress of the AI; in map7 it expands but still takes very long to choose a starting site. In map9 i continued and finally 1 of the AIs expanded but one of the 4 was still searching for a place to embark and land its castle.

Edit2:
Continued on map7 (now clocked >30minutes according to ingame statistics; at max.speed) and half of the AIs still have not placed their castles.. there must be something fishy going on.
[B183-M7-4AI-DEMO1-SAVE1.zip](https://github.com/Pyrdacor/freeserf.net/files/2974600/B183-M7-4AI-DEMO1-SAVE1.zip)

Edit3:
It seems the AI-problems start in mapsize 6, there i have a non-demo game with 3 AIs where 2 of them "refuse" to place their castles. 
[B183-M6-GAME1-3AI-SAVE1.zip](https://github.com/Pyrdacor/freeserf.net/files/2974620/B183-M6-GAME1-3AI-SAVE1.zip)

**Comment by Pyrdacor** [comment]
Ok I know what it is. I will fix this soon.

**Comment by Pyrdacor** [comment]
Please look if it is better with v1.9.1. I recommend to manually install v1.9 before patching to 1.9.1 as v1.9 allows the patcher to patch itself. You won't get new patchers without installing v1.9 manually in the first place.

**Comment by JSettler** [comment]
ok, will test it later, have something to do atm.
