### ISSUE TITLE
AI behaves differently in a loaded game

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#19]
Tested on mapsize 6 (and this time i luckily saved early) with 4 AIs (with all 3 parameters maxed).
Before i reloaded the game the AI behaved normally and even expanded (and i got the freeze-bug again!) then i reloaded and watched minutes of speedrun with the AI becoming static and not making more buildings even with dozens of unemployed serfs.
Something changed in the AIs after the load of the savegame (and it also eliminated the freeze-bug in that particular game)
[B191-MAP6-4AI-DEMO1.zip](https://github.com/Pyrdacor/freeserf.net/files/2975778/B191-MAP6-4AI-DEMO1.zip)

**Comment by JSettler** [comment]
But i have now a theory for a workaround: maybe the AI only becomes static if its reloaded in a very early state (where very few infrastructure exists yet) and if i reload it only after it already expanded it might help the AI in that issue..

**Comment by JSettler** [comment]
Tried the same on a smaller map(4), with fewer AIs(3). First everything normal (until save5) then shortly after that save it froze:
[freeserf_b191_frozen.zip](https://github.com/Pyrdacor/freeserf.net/files/2975862/freeserf_b191_frozen.zip)
(snipping tool wasn't usable while crashed - had to use external device)
Then i reloaded and no more freezes occurred but also no more AI-actions, too (compare save6 with jpg-photo):
[b191-map4-3ai-demo1.zip](https://github.com/Pyrdacor/freeserf.net/files/2975868/b191-map4-3ai-demo1.zip)
In contrast to the photo while frozen, in savegame no.6(after reload) there are no huts built to extend the AI villages and they even 'forgot' to deliver materials to their existing construction sites.
They are completely 'asleep', inactive. Only the already existing jobs get continued: Cutting logs, making boards, fishing, making tools, mine stone, make boats, harvest grain and transporting these things to the castle (or to the boat builder) but not to the construction sites; and no new sites appear, ever. Not even new roads or flags.

**Comment by Pyrdacor** [comment]
About the AI actions. Aggressive AIs will increase their serf-to-knight rate. I now added the condition that they only do so if there are enough generic serfs available. But doing so I found out that the generic serf count is wrong. This seems to be a bug in serf logic so I first have to find out why this happens. It seems that the game thinks that there are many generic serfs when there are none.

**Comment by JSettler** [comment]
Ok. But about the issue of a change in the AI after a reload of a savegame, is that even possible at all?
Today (in ~8-10 hours) i’ll test just that: i‘ll make a AI-only demogame, save it right after the point when the AIs start expanding (as „savegame-1“), then continue that for ~5-10 minutes (in speedrun) then i make „savegame-1A“, then i’ll quit and restart freeserf and reload „savegame-1“ and continue that for the same time length (in speedrun, too) and make „savegame-1B“, these i‘ll then upload for review. (In ~8.5-10 hours i‘ll have the time for it)

**Comment by Pyrdacor** [comment]
Ok I look forward to your test. I could find the reason with the wrong generic serf count. It was indeed a bug which is fixed in patch 1.9.2. Now the AIs should no longer become static.

**Comment by JSettler** [comment]
Something unexpected happened:
While performing the test i got a fatal error:
Log: "Error: [FrameTimer] The target array is not long enough to copy all elements in the collection. Check array index and length." with that it crashed (hard) and i had to end the task.
But this happened in the "original" game (before reloading it), so to reproduce it one has to start a new game with the exact same parameters like this one, else it might not happen.
(i hope the RND-seed can be found in the savegame)
[b192-m5-4ai-savegame.zip](https://github.com/Pyrdacor/freeserf.net/files/2980796/b192-m5-4ai-savegame.zip)

**Comment by JSettler** [comment]
So apparently we are now having nearly a catch-22 situation:
Some hard-crash causing bugs prevent longer testruns which we need to test the difference in AI between originally started and reloaded games. The crash-bugs cant be located with a reloaded game because they are somehow triggered by complex AI-expansion-games which dont happen in reloaded games.

**Comment by JSettler** [comment]
So i have to design the test shorter: i will make the very first save (the splitting point)[named "savegame-1"] right after all 4 AIs have placed their castles. Then i'll save periodically as long as the crash-bugs "allow" it, to a secondary savegame-slot, named "..-1A". When the crash happens i reload "..-1" and let it run at least as long as "..-1A" and will save the outcome to "..-1B" (i'll try to save at a point where the blue AI has at least the same amount of settlers like in the former "timeline").

**Comment by JSettler** [comment]
This time i had more luck and could run it a bit longer before it crashed (with the same error logged).
(all 3 savegames went according to plan and sadly the AI behaved as predicted)
[b192-m5-seed8-4ai-g1-saves.zip](https://github.com/Pyrdacor/freeserf.net/files/2980913/b192-m5-seed8-4ai-g1-saves.zip)
As mapseed i only used the digit '8' (16 times).
(and i'll test if i get the same results with that seed in my next test)

**Comment by JSettler** [comment]
..and now i finally solved my problem with the "freeze-crashes": i just had to deactivate fullscreen while doing tests which could crash *facepalm*
thereby enabling me finally to give you more information:
--------------------------------------------------------------
[building]Delivered unexpected resource.

========== Stack Trace: ==========

   bei Freeserf.Building.RequestedResourceDelivered(Type resource)
   bei Freeserf.Serf.HandleSerfDeliveringState()
   bei Freeserf.Serf.Update()
   bei Freeserf.Game.UpdateSerfs()
   bei Freeserf.Game.UpdateVisuals()
   bei Freeserf.Game.Update()
   bei Freeserf.UI.Interface.Update()
   bei Freeserf.LocalSpectatorViewer.Update()
   bei Freeserf.Renderer.OpenTK.GameView.Render()
   bei Freeserf.FreeserfForm.FrameTimer_Tick(Object sender, EventArgs e)
--------------------------------------------------------------
[crash-18-03-19-20-15-57.zip](https://github.com/Pyrdacor/freeserf.net/files/2980983/crash-18-03-19-20-15-57.zip)

**Comment by JSettler** [comment]
(why does it enlarge the font? i think i can't solve everything today..)

**Comment by Pyrdacor** [comment]
The font enlargement is caused by the assign or star characters which are part of the stack trace.

Ok now I understand your hard crashes. In fullscreen the dialog has no chance to show up but I might switch to windowed mode before opening the error window. Will do this tomorrow.

Thanks for your efforts.

**Comment by JSettler** [comment]
You're welcome :)
Good night.

**Comment by Pyrdacor** [comment]
Ok patch 1.9.3 is out. A crash in fullscreen mode should now leave fullscreen mode first before displaying the error message. So hard crashes should belong to the past. The mentioned error above will now print a bit more information so if you get it again, please post the error message again. Moreover you can scroll the savegame list now by holding right mouse button and drag. So you can have more savegames in the savegame folder.

**Comment by Pyrdacor** [comment]
I found the reason why the AI does nothing after loading but I need some quiet time to work on this. So hopefully this evening.

**Comment by Pyrdacor** [comment]
Ok I found a short time slot and fixed it. AIs should now behave normally after game loading.

**Comment by JSettler** [comment]
Confirmed. (thank you!)
