### ISSUE TITLE
Savegame could not be loaded.

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#22]
Build: 1.9.4

logfile: "Error: [savegame] Failed to load save game: The specified key was not specified in the dictionary."

it was the most recent savegame of:
[b194-m4-4ai-demo1.zip](https://github.com/Pyrdacor/freeserf.net/files/2989689/b194-m4-4ai-demo1.zip)

**Comment by Pyrdacor** [comment]
Fixed it but I wait for releasing a patch till I fix some other things as well.

**Comment by Pyrdacor** [comment]
Patch 1.9.5. should fix this issue.
