### ISSUE TITLE
Critical Error: "[building]Delivered unexpected resource"

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#25]
<span style="font-size:70%">
version: build 1.9.5

mapsize: 3
AIs: 4
testing duration: not long, 3-4 minutes at max.speed

The AI villages were still small when it happened.

[building]Delivered unexpected resource. Index 41, Type GoldSmelter, Resource Plank
</span>

<span style="font-size:60%">
Stack Trace:

   at Freeserf.Building.RequestedResourceDelivered(Type resource)
   at Freeserf.Serf.HandleSerfDeliveringState()
   at Freeserf.Serf.Update()
   at Freeserf.Game.UpdateSerfs()
   at Freeserf.Game.UpdateVisuals()
   at Freeserf.Game.Update()
   at Freeserf.UI.Interface.Update()
   at Freeserf.LocalSpectatorViewer.Update()
   at Freeserf.Renderer.OpenTK.GameView.Render()
   at Freeserf.FreeserfForm.FrameTimer_Tick(Object sender, EventArgs e)

Log file: "Error: [FrameTimer] [building]Delivered unexpected resource. Index 41, Type GoldSmelter, Resource Plank"
</span>
[b195-m3-4ai-demo1-saves.zip](https://github.com/Pyrdacor/freeserf.net/files/2998544/b195-m3-4ai-demo1-saves.zip)
(crash-save included)

--
Edit: Would it be a good idea to make an alternate .exe with single-threading (while we are still in testing-phase)?

**Comment by JSettler** [comment]
Would it be a good idea to make an alternate .exe with single-threading?

**Comment by Pyrdacor** [comment]
I know this error. I added some extra info when this happens again. So if you get it again, please post the log message again.

**Comment by JSettler** [comment]
it crashed again with critical error:
[building]Delivered unexpected resource. Index 402, Type WeaponSmith, Resource Stone, Finished True

========== Stack Trace: ==========

   bei Freeserf.Building.RequestedResourceDelivered(Type resource)
   bei Freeserf.Serf.HandleSerfDeliveringState()
   bei Freeserf.Serf.Update()
   bei Freeserf.Game.UpdateSerfs()
   bei Freeserf.Game.UpdateVisuals()
   bei Freeserf.Game.Update()
   bei Freeserf.UI.Interface.Update()
   bei Freeserf.LocalSpectatorViewer.Update()
   bei Freeserf.Renderer.OpenTK.GameView.Render()
   bei Freeserf.FreeserfForm.FrameTimer_Tick(Object sender, EventArgs e)
   
---------------------------------------------------------------------------------------------------------------------

Log file: " Error: [FrameTimer] [building]Delivered unexpected resource. Index 402, Type WeaponSmith, Resource Stone, Finished True "
[b196-m9-demo1.zip](https://github.com/Pyrdacor/freeserf.net/files/3005374/b196-m9-demo1.zip)

**Comment by Pyrdacor** [comment]
Ok I don't know why this happens. The problem is that a serf brings a wrong resource to a building. It seems to always be a construction material (planks or stone). But when the buildings is already built. As the reason is very hard to find, the current fix is to add the wrong resource back to the castle. This should avoid the crash for now. I will investigate later to find the reasons or maybe just implement, that the resource is transported back to the nearest inventory. But for now I use the mentioned fix to concentrate on other things.

But I'll wait for releasing the patch a bit and test some longer runs myself first.

**Comment by Pyrdacor** [comment]
Ok I added patch 1.9.7. This patch will also improve game performance as it improves AI flag linking performance very much. I also found and fixed another crash which wasn't tracked yet. 1.9.7 seems to run pretty stable imho.
