### ISSUE TITLE
Critical Error: "The index is greater than or equal to the length of the array, or the number of elements in the dictionary is greater than the available space from the index to the end of the target array."

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#26]
version: build 1.9.5
type: 2-AI demo
map: 3
time elapsed: ~6-8 minutes

Der Index ist größer oder gleich der Länge des Arrays, oder die Anzahl der Elemente im Wörterbuch ist größer als der verfügbare Platz vom Index bis zum Ende des Zielarrays.

========== Stack Trace: ==========

   bei System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 index)
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Freeserf.Game.UpdateRoads()
   bei Freeserf.Game.UpdateVisuals()
   bei Freeserf.Game.Update()
   bei Freeserf.UI.Interface.Update()
   bei Freeserf.LocalSpectatorViewer.Update()
   bei Freeserf.Renderer.OpenTK.GameView.Render()
   bei Freeserf.FreeserfForm.FrameTimer_Tick(Object sender, EventArgs e)

Log file: "Error: [FrameTimer] The index is greater than or equal to the length of the array, or the number of elements in the dictionary is greater than the available space from the index to the end of the target array."

[b195-m3-2ai-demo1-saves.zip](https://github.com/Pyrdacor/freeserf.net/files/2999824/b195-m3-2ai-demo1-saves.zip)

(this time there was no save option in crash-handling window)

**Comment by Pyrdacor** [comment]
Should be fixed with 1.9.6

**Comment by JSettler** [comment]
Ok will test it in ~9-10 hours.
