### ISSUE TITLE
Update doesn't work

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#27]
After starting .exe the patcher launches and it looks as if it does update, but ingame it still shows v1.9.6 and after a second start of the .exe the patcher runs again and the properties of the exe say 1.9.6.0, too.

Edit:
Ok, the workaround is to unpack v1.9[.0] again into another dir and patch directly from 1.9.0 > 1.9.7

**Comment by Pyrdacor** [comment]
This is strange. Maybe some file inside the folder was open while you patched?

**Comment by Pyrdacor** [comment]
The patcher is a very basic tool which is not meant to be part of the later release. If the later game will have a patcher, it will be reworked.

**Comment by JSettler** [comment]
I deleted the (non-patchable 1.9.6) dir and made a new one (with my user/data files moved there), so i can‘t test that issue anymore, sorry.

**Comment by Pyrdacor** [comment]
No problem.
