### ISSUE TITLE
Question: will AI ever build larger military buildings (like towers=6 knights and strongholds=12 knights) ?

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#28]
(eg. to better defend its stocks or at tactical choke points etc.)

**Comment by Pyrdacor** [comment]
Not at the moment. I will add this soon. AIs have a preference for the 3 different military buildings but at the moment they only build huts.

**Comment by Pyrdacor** [comment]
I am implementing and testing this right now.

**Comment by Pyrdacor** [comment]
Patch 1.9.8 should fix this. The rate of these buildings may be a bit low. Every character prefers different military buildings so some will build larger ones faster than others.
