### ISSUE TITLE
AI only crafts swords and has no shields

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#29]
i don't know when that effect starts, but after a very long speedrun (>50 minutes) i checked his castles and discovered that several AIs had over 100 swords stored but 0 shields.
[b197-m3-4ai-saves.zip](https://github.com/Pyrdacor/freeserf.net/files/3009376/b197-m3-4ai-saves.zip)

But the game runs extremely stable now (at least on m3 map, i'll test m9 later), thank you for improving it that far!

**Comment by Pyrdacor** [comment]
Crafting swords or shields is not part of the AI. It is serf logic of the weaponsmith. But I saw this behavior too. I will look if I can find something.

**Comment by Pyrdacor** [comment]
I will have a closer look at this in the future. For now I will close this till I get some more evidence of this.
