### ISSUE TITLE
game crashes on startup

### ISSUE THREAD

**Issue by tlongstretch** [Pyrdacor/freeserf.net#3]
I can't get the Build1.0 version to run.  This is the first I've tried running your .net version of Freeserf.  I don't know anything about C# or .NET development so I'm not sure if there are some dependencies I'm unaware of.  I placed SPAE.PA in the same directory as freeserf.net.exe.   Visual Studio says the crash is on 

System.IO.FileNotFoundException: 'Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'

I'm running windows7 64bit

**Comment by tlongstretch** [comment]
I downloaded your compiled exe, btw, didn't try compiling it from source.

**Comment by Pyrdacor** [comment]
Hey you have to install the .NET framework. Try version 4.6.1. You can download it directly from Microsoft. Please tell me if it worked.

**Comment by tlongstretch** [comment]
After uninstalling and re-installing 4.6.1 I got same error, but I googled it and it seems updating to 4.7.1 fixes it, which it did for me

**Comment by tlongstretch** [comment]
https://github.com/dotnet/standard/issues/485

https://github.com/dotnet/announcements/issues/31


I have the same problem and got fixed when updating the .NET Framework from 4.6.2 to 4.7.1
--
