### ISSUE TITLE
AI settlement has a circular traffic-jam, blocking its castle and crippling the AI completely.

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#32]
The yellow AI ("King Rolph VII") has effectively stalemated itself.
Though it has a stock built, it doesn't help because >99.9% of its resources are still in the (blocked) castle.
[b198-m9-ai4-demo1-savegames.zip](https://github.com/Pyrdacor/freeserf.net/files/3014555/b198-m9-ai4-demo1-savegames.zip)
But apart from this issue the AIs are prospering (and building towers & strongholds!) and the game runs very stable, no crashes to report yet.

**Comment by Pyrdacor** [comment]
This is now resolved by putting the serf at the castle back into the castle after some time. I wait to add the next patch though. I also have to fix that a serf is even leaving the castle when there are waiting serfs at the castle flag. That should not happen and had caused the issue in the first place. In the original game this didn't happen.

**Comment by Pyrdacor** [comment]
Patch 1.9.11 should solve it.

**Comment by Pyrdacor** [comment]
Patch 1.9.17 will now stop serfs from leaving the castle if there are waiting serfs.
