### ISSUE TITLE
Is the 'changing of the guard' button functionally implemented?

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#33]
I recalled that in an earlier (but recent) version the button for changing your knights didn't work.
(It's supposed to strengthen the staff of the military buildings, by exchanging lower ranked soldiers with higher ranked ones.)

**Comment by Pyrdacor** [comment]
Did you try to double click it?

**Comment by JSettler** [comment]
ah! ok i only single-clicked it, thanks.

**Comment by Pyrdacor** [comment]
Some functions are protected because they have great impact. This was also the case in the original. There was the special click (left + right mouse button). This is still possible but the double click will do the same and is more common.
