### ISSUE TITLE
Critical Error: "[serf] The object reference was not set to an object instance."

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#35]
(i let the AIs develop for about 10-15 minutes, and watched only)

========== Stack Trace: ==========

   at Freeserf.Serf.HandleSerfWalkingStateDestReached()
   at Freeserf.Serf.HandleSerfWalkingState()
   at Freeserf.Serf.Update()
[b198-m3ai-game1-saves_(plus logtxt).zip](https://github.com/Pyrdacor/freeserf.net/files/3015571/b198-m3ai-game1-saves_.plus.logtxt.zip)

**Comment by Pyrdacor** [comment]
This is hopefully fixed in 1.9.10
