### ISSUE TITLE
AI attacking with one knight at a time

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#37]
Instead of making an attack with 5 knights, the AI makes 5 attacks with 1 knight.

**Comment by JSettler** [comment]
Do you have a savegame? (and welcome to the beta-tester team! :)

**Comment by Vershner** [comment]
I have a save from that game, but it's an hour or so since the AI attacked. It doesn't seem to want to attack again. 
[TEST1.zip](https://github.com/Pyrdacor/freeserf.net/files/3015773/TEST1.zip)

**Comment by Pyrdacor** [comment]
Hm I checked and for me AIs attack with 3, 5 or even more knights at a time. It depends on the military building occupation setting which depends on the amount of available knights and the AI character. Try Sollok the Joker as an enemy and you will see that it works.

**Comment by Vershner** [comment]
The AI did send 5 knights at the same time, but they came as 5 individual attacks rather than one, so I got 5 messages that I was being attacked.

**Comment by Pyrdacor** [comment]
Do you mean the knights arrived at different times due to moving delays or did just the game pop up 5 notifications while the knights arrived almost at the same time?

**Comment by Vershner** [comment]
The latter. The knights were not coming from far away. It looked like a normal attack of 5 knights, but I got 5 separate notifications.

**Comment by Pyrdacor** [comment]
Should be fixed in patch 1.9.15
