### ISSUE TITLE
AI builds military buildings too densely 

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#38]
The AI frequently builds military buildings within 2 squares of each other. I can't remember what the limit was in the original, but more like 4 or 5. 

Edit - just tested with the original Amiga version and actually the limit is only 2.5 hexagons vertically. 2 hexagons horizontally. The AI just didn't build them so densely.

**Comment by Pyrdacor** [comment]
Should now be better with patch 1.9.9
