### ISSUE TITLE
unable to click on certain areas of map

### ISSUE THREAD

**Issue by tlongstretch** [Pyrdacor/freeserf.net#4]
Sometimes just a few tiles, but I've seen a large chunk of the map where nothing can be selected.  I've only played one game so far but I see a few instances of this.  Often when trying to connect a newly built building's flag the flag cannot be connected in some directions.

**Comment by Pyrdacor** [comment]
Yeah I know this issue. But I think it only happens for even map sizes. Which map size did you use?

**Comment by tlongstretch** [comment]
Not sure, whatever the default is.

**Comment by Pyrdacor** [comment]
Hm the default is 3, so an odd map size. Should not happen there. I'll have a look into it.

**Comment by Pyrdacor** [comment]
Can you test with version 1.2 please? Should be fixed now.
