### ISSUE TITLE
After battle serfs get stuck

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#40]
After a battle, a number of mines were burnt, and two issues occurred. 
These two builders became stuck on screen, not on the map. (they move around as I scroll)
![stuck](https://user-images.githubusercontent.com/41204375/55122562-52ee3d80-50f7-11e9-996b-a60078a6a431.png)

These miners are stuck in place on the map. (they don't move when I scroll, but they don't go home)
![stuck2](https://user-images.githubusercontent.com/41204375/55122688-b37d7a80-50f7-11e9-847a-3436c654c15a.png)

**Comment by Pyrdacor** [comment]
Might be fixed with 1.9.20. If not let me know.
