### ISSUE TITLE
Boatman doesn't stay on his path

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#42]
When I make a water path, the boatman carries his boat to the path, paddles down the path once, then goes home again, back to the castle or stock.

**Comment by JSettler** [comment]
This could be a regression. I recall to have seen ferry men working normally in earlier version(s).

**Comment by Vershner** [comment]
After testing a bit further, it does sort of work if there's objects waiting. It seems the boat man goes home if there's nothing for him to carry.

**Comment by Pyrdacor** [comment]
Fixed the behavior in 1.9.10
