### ISSUE TITLE
Sometimes cannot select position

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#44]
It's a difficult one to explain, but occasionally it will become difficult or even impossible to select a particular hexagon. Clicking on its central point will just select one of the ones next to it. A similar thing happens with the path direction icons. 
On one game this became so bad it was unusable, but I haven't been able to reproduce that. Zooming in and out, scrolling, and switching in and out of fullscreen don't seem to make any difference.

**Comment by Vershner** [comment]
Here's an example of the issue with the path icon. It's almost impossible to select the rightmost (light-red) path icon. I think there is one or two pixels above and to the right of the icon that will actually select it. 

![cannotselect](https://user-images.githubusercontent.com/41204375/55162688-3d612e00-5160-11e9-90d0-61cec1758341.png)

[CANNOTSELECT.zip](https://github.com/Pyrdacor/freeserf.net/files/3018221/CANNOTSELECT.zip)

**Comment by Vershner** [comment]
Here's an example of selecting hexagons. Try to select the peak of the mountain at the north of my territory, the selection does not line up with the mouse pointer. 
[SELECTOUT.zip](https://github.com/Pyrdacor/freeserf.net/files/3026567/SELECTOUT.zip)

**Comment by Pyrdacor** [comment]
Should be much better with patch 1.9.16
