### ISSUE TITLE
Crash: [serf]Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#45]
I didn't have a pig farm, but presumably the AI did. 

--------------------------------------------------------------------------------------

[serf]Index was outside the bounds of the array.

========== Stack Trace: ==========

   at Freeserf.Serf.HandleSerfPigfarmingState()
   at Freeserf.Serf.Update()

[crash-28-03-19-13-42-03.zip](https://github.com/Pyrdacor/freeserf.net/files/3018195/crash-28-03-19-13-42-03.zip)

**Comment by Pyrdacor** [comment]
This may be fixed in 1.9.10. Let me know if it happens again.
