### ISSUE TITLE
New freeze(crash?) problem with B1.9.9  ..

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#46]
..after watching a long game between 3 AIs on mapsize 4 (in 1player-mode) it just froze without any prior warning. The logfile contains over 10k lines saying "Error: [data] Failed to get animation #128 phase #48 (got only 48 phases)"
It happened ~5-15 minutes after the last save.
(This time it didn't unmaximize the game-screen, therefore i couldn't copy the stack trace. I don't even know if there was such a window present, because all i could do was to reset back to taskman.)
[Build199-Map4-3AIs-game1-saves.zip](https://github.com/Pyrdacor/freeserf.net/files/3025734/Build199-Map4-3AIs-game1-saves.zip)

**Comment by Pyrdacor** [comment]
Hm it's hard to find the reason. In patch 1.9.10 I changed the fullscreen mode in a way that the window won't block other windows. So maybe next time you can switch to the error window and copy the stack trace.
