### ISSUE TITLE
crash on deleting flag

### ISSUE THREAD

**Issue by tlongstretch** [Pyrdacor/freeserf.net#5]
Burnt a building connected to a road, error when deleting the attached flag.  The given key was not present in the dictionary"

"
![capture](https://user-images.githubusercontent.com/45954803/52456094-34ce7d00-2b4b-11e9-8f5d-6750ab780389.PNG)

**Comment by Pyrdacor** [comment]
I tried to reproduce the error but could not do so. Maybe the error comes from somewhere else and it was only coincidence that it happened when you deleted the flag? If you can reproduce this, please let me know.

**Comment by tlongstretch** [comment]
I'll re-open if I see it again.
