### ISSUE TITLE
Knights retreat after win

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#50]
After winning a fight, only the first knight goes into the enemy building. The others go home. They should fill the building and only the remaining knights go home.

**Comment by Pyrdacor** [comment]
They only fill the building if the knight occupation setting is set to medium or high. Are you sure this setting was set to these values?

**Comment by Vershner** [comment]
Yes, the guard hut was right next to the enemy so it would have been using high.

**Comment by Pyrdacor** [comment]
I just tried and the captured hut is filled with 3 knights every time.

**Comment by Vershner** [comment]
Ok I'll test further and try to get a save game if it happens again.

**Comment by Pyrdacor** [comment]
Thanks
