### ISSUE TITLE
Crash: [serf]Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#51]
[serf]Object reference not set to an instance of an object.

========== Stack Trace: ==========

   at Freeserf.Serf.HandleSerfIdleInStockState()
   at Freeserf.Serf.Update()

-----------------------------------------------------------------------------------

[crash-31-03-19-19-38-33.zip](https://github.com/Pyrdacor/freeserf.net/files/3027011/crash-31-03-19-19-38-33.zip)

**Comment by Pyrdacor** [comment]
Hopefully fixed with patch 1.9.11
