### ISSUE TITLE
Periodic performance slowdowns.

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#52]
Yesterday i got a game where this happened, after watching 3 opponent AIs (in a 1-player game) without placing my castle: i watched at top-speed and then it started to slowdown to a crawl for some seconds and got faster after that. The period where this happened got successively shorter and the slowed-down timelength grew. (I‘m on my tablet so i have currently no savegame, but today evening i‘ll upload it if you wish)
Parameters were: build 1.9.11;  mapsize 4 ;  3 hardest AI(with highest levels) and myself on lowest levels. (The random-seed was the same as in the savegame where the new freeze happened. (The upload should still be there))

Edit - it happened after a long time of watching, roughly ~10-20 minutes, after a „2-AI hut-building-race“ to reach a mountain range (it was fun to watch, never saw that behaviour before!) the 2 AI finally had a chain of a handful of guard huts each , next to another.

**Comment by Pyrdacor** [comment]
I saw this too and already added it to my ToDo list. My guess is that it has to do with looking for geospots. Because the search is related to the amount of military buildings this may slow down in later game whenever an AI needs to find minerals. I will have a look at this when I got more time on hands.

**Comment by JSettler** [comment]
(Thanks.)

**Comment by Pyrdacor** [comment]
It's always good to have savegames to test, so if you don't mind, please update it. :)

**Comment by Pyrdacor** [comment]
I found a bottleneck in performance that I improved in patch 1.9.14. But I don't know if this solves all the performance issues. Maybe you could test.

**Comment by JSettler** [comment]
Yes! It has really given the game a kick! Fun to watch it now :)
The new version (1.9.14) was like an infusion of adrenaline in that old savegame, the AI villages blossomed to new activity ^^
(to satiate anyones curiosity - it was this savegame: 
[b1911-m4-ai3-game2-b1914-saves.zip](https://github.com/Pyrdacor/freeserf.net/files/3031690/b1911-m4-ai3-game2-b1914-saves.zip)
started in build1.9.11 and the last savegame was saved within build1.9.14)
