### ISSUE TITLE
Bonus mission

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/freeserf.net#53]
Hi guys. I added a bonus mission (mission 31). This will be my one-on-one AI test comparing the best AI character to a human player. The AI has a bit more resources and a better starting point. If you want, you can try with patch 1.9.13.

**Comment by Pyrdacor** [comment]
I will fine-tune the AI from time to time so it will be extremely hard to beat it.

**Comment by JSettler** [comment]
Thank you! :) will try later (at evening)

**Comment by Pyrdacor** [comment]
If Yoki is the dark guy from mission 30, then yes. But you will have no starting supplies and are close to him.

**Comment by JSettler** [comment]
Wow! Sounds good. (Not unlike one of my most recent games)
(Btw. Yoki is also found in mission 29.

**Comment by JSettler** [comment]
Do you plan to make him later selectable in custom games (after the main game is finished with debugging and optimizing etc.) ?

**Comment by Pyrdacor** [comment]
Yes I see no reason why this guy should only be available in missions. It's a good idea that one has to unlock him by defeating him in missions.

**Comment by JSettler** [comment]
Even in AI-only demo-games?

**Comment by Pyrdacor** [comment]
I think this would break fun for those who only want to play custom games and no missions. My plan for the future is to allow mod support like additional characters, missions, buildings and so on. Maybe there would be the place for such things. :)
