### ISSUE TITLE
Question about knight-fights in open range.

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#54]
Manual mentioned, that one could send a counter attack to thwart an incoming attack, so that when these two knight-groups meet while travelling, they would instantly challenge each other to a fight (sometimes long before they reach their designated target).

**Comment by Pyrdacor** [comment]
I don't know a feature for this. But of course you can attack a nearby enemy hut so that your knights walk in the direction of the incoming troups. If knights meet in a certain range, they will fight in open range.

**Comment by JSettler** [comment]
Ok, so this is a viable strategy to defend an important single guard-hut (if an enemy hut is nearby the path of the incoming knights)
