### ISSUE TITLE
Feature request: Amiga music & sounds

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#55]
It's right to use the PC graphics as they are 256 colour rather than the Amiga's 64, (and you don't have to figure out planar extra-halfbrite images) however, the Amiga music and sound effects are far superior so it would be nice to have the option to use these.

**Comment by Pyrdacor** [comment]
If you are willing to test amiga data, I could enable this option easily. But at the moment there is only an all-in possibility which means all data from DOS or all data from amiga.

**Comment by Vershner** [comment]
Happy to test it. I have the Amiga files, but they don't work with the current C++ version. WDigger is looking into it.

**Comment by Pyrdacor** [comment]
The first step was to allow to change the data file. You can do this with patch 1.9.19 in the user config file. Just set the value `datafile` under section `game` to the filename of the amiga data file (without path). The file must be located in the same directory as the exe file. If the key `datafile` does not exist, you may add it or just open and close the game.

I did not test amiga data sources yet so don't expect them to work. But we can now start to test this is bugfix loading perhaps.

**Comment by Pyrdacor** [comment]
I spent some time with Amiga data loading a few weeks ago and made some progress but unfortunately my time is very limited at the moment. But this is on top of the priority list now.

**Comment by Pyrdacor** [comment]
I fixed some bugs in amiga data loading. Now the game at least runs with amiga files. The map graphics look quite messy but not too much. Music is loading but not playing yet. I will focus on that now. Sounds seem to work though.

**Comment by Pyrdacor** [comment]
Finally the Amiga music is playing after many hours of trying to make it work. There are some small bugs like pauses. I will have a look at it later.

Moreover the user config now stores preferred data for graphics, sounds and music. Default is graphics and sound from DOS and music from Amiga. This can be changed manually inside the user config file (maybe later in the game options dialog). So you can now mix DOS and Amiga data (e.g. DOS graphics with Amiga music). Update comes in a minute.

**Comment by Pyrdacor** [comment]
Ok update 1.9.22 is available and should contain the mentioned stuff.

**Comment by Pyrdacor** [comment]
I close this. It isn't perfect yet but the feature is available. Feel free to reopen later.
