### ISSUE TITLE
Got some crashes with a 4-AI-demogame.

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#56]
These might be hard to reproduce and they didn't gave a custom stack-trace error-window but a standard Windows-Crash-Handling window:

Problem signature:
   Problem Event Name: clr20r3
   Issue signature 01: Freeserf.net.exe
   Issue signature 02: 1.9.15.0
   Problem signature 03: aa82bef1
   Problem signature 04: Freeserf.Core
   Issue Signature 05: 1.0.0.0
   Issue signature 06: b5b50d03
   Problem signature 07:49
   Issue Signature 08: 9d
   Issue signature 09: System.NullReferenceException
   OS Version: 6.1.7601.2.1.0.768.3
   Locale ID: 1031
   Additional information 1: 0a9e
   Additional information 2: 0a9e372d3b4ad19135b953a78882e789
   Additional information 3: 0a9e
   Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

That was the crash i got with 1.9.15, the one with 1.9.14 (same savegame) was very similar; had to reset-switch to taskmanager to even be able to see/copy the contents of that CrashHandling-Window.
[b1914-sav02-b1915-savegames.zip](https://github.com/Pyrdacor/freeserf.net/files/3035332/b1914-sav02-b1915-savegames.zip)

Edit - It might be related to #46.
and i forgot the logfile:
[log.txt](https://github.com/Pyrdacor/freeserf.net/files/3035360/log.txt)

Edit2:
Oh i forgot to mention something strange: in loaded demo-games one can sometimes act like as if being in a 1player-game and changing settings (but i did not make permanent changes to that AI-game, i reverted the setting back and the crash was not related to this)

**Comment by JSettler** [comment]
It might be related to #46.
and i forgot the logfile:
[log.txt](https://github.com/Pyrdacor/freeserf.net/files/3035358/log.txt)

**Comment by Pyrdacor** [comment]
The strange thing is fixed in 1.9.16. If you load an AI-only game you won't be able to change things anymore and you will be able to switch AI players. Loading a game always used the "player" view instead of the "spectator" view which was only used for new AI-only games. Now when loading, the view is changed dependent of the saved game settings.

**Comment by Pyrdacor** [comment]
Hard to find but now at least unhandled errors should be written to the log file with some extra info. I also fixed the errors occuring in your log file (which have nothing to do with the crash I think). Try patch 1.9.18.
