### ISSUE TITLE
Another AI-village traffic-jam

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#57]
..near the magenta (Sollok) HQ. It clogs up a junction with 6 pathways right next of a guard hut (the hut is between HQ and junction).
(My hunch is, that this situation would last until a border-change destroys the path where the bugged serf is causing the jam.)
[build1917-map3-3ai-game1-savegames.zip](https://github.com/Pyrdacor/freeserf.net/files/3040403/build1917-map3-3ai-game1-savegames.zip)

**Comment by Pyrdacor** [comment]
This is not reproducable with version 1.9.21. Can you check if it is resolved for you as well?
