### ISSUE TITLE
question about serf/resource pathfinding on roads

### ISSUE THREAD

**Issue by tlongstretch** [Pyrdacor/freeserf.net#6]
I was looking for a way to calculate the flag path to the castle/stock.  I figure that in order for serfs and resources to find their destination the existing FreeSerf game code must have it.  However, I have looked at the code for a while and I don't understand it.  It seems serfs and resources have destinations, but I can't find the code that figures out which direction's path gets it closer to the final destination.   I see you wrote a  pathfinder function for this, but I am wondering how the original code does it?  I think the logic is hidden in bit-shifting that I am not understanding.   Any ideas?

**Comment by tlongstretch** [comment]
It seems like the key is if a Flag's "search_dir"  Direction matches the search_dir of the adjacent flag that the route is correct.  I don't understand how a flag can have a single fixed search_dir though unless it is constantly redefined and re-used by every single FlagSearch call.   This may be the case, which would prevent flag searches this way from being multi-threaded.  Even if it is the case, it still isn't clear to me where the logic is to set these search_dirs to point in the right place.   It seems in order for them to be set correct, the search must have already been done and they are simply being followed.

**Comment by Pyrdacor** [comment]
I think each serf performs a flag search at each flag it reaches (see HandleSerfWalkingState in Serf.cs). The serf stores the destination when leaving a building and then searches at each flag along the way. Not the best in regards of performance but it is safe if roads change while the serf is moving.

**Comment by Pyrdacor** [comment]
I have created a pathfinder for roads but I don't use it yet for serfs. I will rework serf logic at a later point.

**Comment by Pyrdacor** [comment]
About how the dir is set: Every directly connected flag gets a search dir value equal to the direction pointing to that flag. All those flags are added as a flag search source. The flag search sets the search dir of every flag it finds to the search dir of the source flag. If a road was found, the search is immediately stopped. Therefore the search dir will be that of the first source flag that has a valid road to the destination. The search is counter clockwise.

**Comment by Pyrdacor** [comment]
I didn't understand it until now either but now it makes sense. Thanks for the question. It motivated me to have a closer look at this and now I learned something. :)

**Comment by tlongstretch** [comment]
Thanks you!   I was interested in this because I assumed it must be faster than using a pathfinder.  If it isn't faster I don't see much point in using it and I will write a road pathfinder (pretty much identical to what you have).   

WIth the original Serf City/Settlers game, I recall being annoyed that destroying a road (only to rebuild it more efficiently) would cause any en-route resources that were destined to pass through that road to immediately be sent back to the inventory.   However, now that you mention it, I don't think that serfs/knights ever had this issue.  I think the road finding logic in the original game works differently for serfs and resources.   I'll have to compare the two.

One optional game improvement I believe would be to change the resource routing to be re-evaluated at every flag (like serfs?) so that roads can be re-routed without causing en-route resources to be rejected.  

There are probably a lot of tradeoffs in the original game code to minimize memory usage, where in modern times it may make more sense to use memory to save cpu cycles.

**Comment by tlongstretch** [comment]
Also, it sounds like if the flag.direction value is used for FlagSearches, that they cannot be made multithreaded.   I don't know where most cpu cycles are spent, but I suspect resource routing is a big one and maybe changing the entire routing code to be multithreaded would help with performance.

**Comment by tlongstretch** [comment]
Another thing... I wonder how important it really is to consider "actual road cost" including hieght differences.  My experience has been that the shortest route is usually the best even if it is a bit hilly, and I am skeptical that the efficiency gained by comparing road height makes is significant.

**Comment by Pyrdacor** [comment]
I have a different opinion about that. One road segment can take longer than 3 others depending on the height differences. This may not matter with long roads but it will with short roads. The other thing to consider is traffic. Avoiding hilly roads may improve resource transportation very much.

**Comment by tlongstretch** [comment]
I agree with you that hill roads are much slower than flat ones, however while playing I feel that there is little choice.  If you want to connect a building that is on a slope, you either have to traverse straight up the hill or take a longer zig-zag path to reduce the peak slope.  Given those two options I can’t tell much difference in the end result. 

For long roads, there is freedom to go avoid slopes if your endpoints are at the same level.  But I find it rare that there is a clearly preferred route.  

I do take great care in setting up the first few roads around my castle.  Perhaps if pathfinding becomes a bottleneck it would be worth optimizing only the first few roads.

Maybe I am worrying about nothing, I’m not sure how expensive the road cost calc is.  For the moment I am skipping it.  I will see how sane my AI roads look when only considering length and flag count.

**Comment by tlongstretch** [comment]
Man, I was going crazy struggling with getting the correct end Directions between arbitrary flags when pathfinding roads, because you cannot determine other_end_dir for a given dir by reversing dir.  I looked to see how you are doing and I am going to use your way.   I was trying to NodeSearch a flag path, then follow the dirs between flags of each segment of the winning path.  I see you are pathfinding the NodeSearch as you go, which solves the other_end_dir problem I have.

**Comment by tlongstretch** [comment]
Ah I spoke too soon.  Upon closer look, you are just fetching the Road object *because your game implementation stores Road objects for every path*, which the C/C++ freeserf does not.  Because I do not want to modify the original code at this time I will have to write a modified search that builds Roads as it goes.
