### ISSUE TITLE
Question: Should user.cfg be editable? 

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#60]
I tried entering a different resolution, but it was ignored, and after reloading the game it was reset to 1280x960.

**Comment by Pyrdacor** [comment]
Did you changed it while the game was running? If you change it when the program is not running, it should work.

**Comment by Pyrdacor** [comment]
I looked into it and I found some bugs with the user config. Please try with patch 1.9.19. You may now also change the data file in it. So maybe you could try to load amiga sources. I won't expect them to work though, yet. :)

**Comment by Vershner** [comment]
The resolution setting works if I set it to anything lower than 1280x960. If I set to anything higher, it ignores that and resets the file to 1280x960.
The Amiga has multiple data files: - 
gfxchip
gfxfast
gfxheader
gfxpics
music
sounds

**Comment by Pyrdacor** [comment]
The resolution is capped at 1280x960 so this is correct behavior. This might be changed in the future.

About the amiga files. I will have to look into it when I got more time. At the moment I have much stuff to do.
