### ISSUE TITLE
Cannot rebuild on mine plot

### ISSUE THREAD

**Issue by Vershner** [Pyrdacor/freeserf.net#62]
If I demolish a mine, the miner remains stuck in position and I cannot build a new mine on that position. I can place the mine, and materials are delivered, but no builder comes, even though builders are available. 
I've tested with other types of building and so far it seems only mines are affected.

In this save gave you can see the mine plot to the north-west of my castle. 
[NOBUILDER.zip](https://github.com/Pyrdacor/freeserf.net/files/3049789/NOBUILDER.zip)

**Comment by Pyrdacor** [comment]
Should be fixed in patch 1.9.20.
