### ISSUE TITLE
Able to send archaeologist to non-flag area

### ISSUE THREAD

**Issue by GORE84** [Pyrdacor/freeserf.net#66]
Clicked by accident next to flag to send archaeologist caused crash.

>  Object reference not set to an instance of an object.
> 
> ========== Stack Trace: ==========
> 
>    at Freeserf.Game.SendSerfToFlag(Flag dest, Type type, Type resource1, Type resource2)
>    at Freeserf.UI.PopupBox.HandleAction(Action action, Int32 x, Int32 y, Object tag)
>    at Freeserf.UI.PopupBox.HandleButtonClick(Object buttonTag, Int32 x, Int32 y)
>    at Freeserf.UI.PopupBox.PopupBox_ButtonClicked(Object sender, ClickEventArgs args)
>    at Freeserf.UI.Button.HandleClickLeft(Int32 x, Int32 y)
>    at Freeserf.UI.GuiObject.HandleEvent(EventArgs e)
>    at Freeserf.UI.GuiObject.HandleEvent(EventArgs e)
>    at Freeserf.UI.GuiObject.HandleEvent(EventArgs e)
>    at Freeserf.UI.Interface.HandleEvent(EventArgs 
> 

[https://i.imgur.com/tDJFekw.jpg](https://i.imgur.com/tDJFekw.jpg)

**Comment by Pyrdacor** [comment]
Thanks for the report. Will have a look at it soon.

**Comment by Pyrdacor** [comment]
How did you do that? I can only send geologists if I double-clicked a flag before.

**Comment by GORE84** [comment]
I was able to reproduce it by holding down right mouse button and scroll map and same time double click on flag.

**Comment by Pyrdacor** [comment]
Should be fixed in v1.9.23.
