### ISSUE TITLE
Startup error (font error)

### ISSUE THREAD

**Issue by GORE84** [Pyrdacor/freeserf.net#74]
Trying v1.9.27-inputfix gives me this error while trying to start up the game.

I'm using Win7

> 
> Could not find a part of the path 'F:\FreeSerf\assets\ui_font.png'.
> ========== Stack Trace: ==========
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at Freeserf.Data.Sprite.CreateFromFile(String filename, Nullable`1 colorkey)
>    at Freeserf.Render.TextureAtlasManager.AddAll(DataSource data, String assetPath)
>    at Freeserf.Renderer.OpenTK.GameView..ctor(DataSource dataSource, Size virtualScreenSize, String assetPath, DeviceType deviceType, SizingPolicy sizingPolicy, OrientationPolicy orientationPolicy)
>    at Freeserf.FreeserfForm.FreeserfForm_Load(Object sender, EventArgs e)

**Comment by Pyrdacor** [comment]
I was missing to provide a file in the release. Try to download v1.9.28. It should work.
