### ISSUE TITLE
[Serf] Path has no other end flag in selected dir.

### ISSUE THREAD

**Issue by GORE84** [Pyrdacor/freeserf.net#75]
Watching AI play against each other, this happends.

Critical error:

> [Serf] Path has no other end flag in selected dir.
> 
> ========== Stack Trace: ==========
> 
>    at Freeserf.Serf.HandleSerfWalkingStateDestReached()
>    at Freeserf.Serf.HandleSerfWalkingState()
>    at Freeserf.Serf.Update()

**Comment by Pyrdacor** [comment]
Did you load this game or was it a fresh new game?

**Comment by GORE84** [comment]
It was fresh game.

**Comment by Pyrdacor** [comment]
This might be fixed in v1.9.29. I close this until it reoccurs.
