### ISSUE TITLE
Game crash (unknown reason)

### ISSUE THREAD

**Issue by GORE84** [Pyrdacor/freeserf.net#79]
Started an AI 1v1 game and left it running while doing other things. Returning back after an hour this error message was up:

> [Serf] Object reference not set to an instance of an object.
> 
> ========== Stack Trace: ==========
> 
>    at Freeserf.AIStates.AIStateCraftTool.Kill(AI ai)
>    at Freeserf.AI.NotifyCraftedTool(Type tool)
>    at Freeserf.Player.NotifyCraftedTool(Type tool)
>    at Freeserf.Serf.HandleSerfMakingToolState()
>    at Freeserf.Serf.Update()

**Comment by Pyrdacor** [comment]
Thanks. Found the issue and fixed it in code. Will provide a game update soon.

**Comment by Pyrdacor** [comment]
Should be fixed in v1.9.33.
