### ISSUE TITLE
savegames

### ISSUE THREAD

**Issue by JSettler** [Pyrdacor/freeserf.net#8]
'Since version 1.3 savegames should work correctly' - How?
i can't get it to load any savegame - clicking on them renders no reaction and clicking on start (in the load menu) does nothing. (the exit button closes the game altogether)
The log says 'Error: [savegame] Failed to load save game: A closed file can not be accessed.'

But thanks for continuing this great project!  :-)
(my "programming knowledge" is very limited else i would help)

where do the savegames get stored?

**Comment by Pyrdacor** [comment]
If you select a savegame in the list you should be able to start it by clicking the Start button. This works for me. I will have a look at it. There seems to be something wrong with the file access. I already saw another bug after loading a savegame. Seems that the interface is not set up correctly as well.

Thank you for your feedback. I love the game so it is an honor to work on this project.

The savegame is stored in the default savegame directory which is something like "C:\Users\username\Saved Games" as I remember correctly.

**Comment by Pyrdacor** [comment]
I found a bug which should have caused your issue. I fixed it in v1.4. Can you try with this version? Do you try to load a legacy savegame from the original game or is it a savegame of freeserf.net itself? If the latter is the case, with which version did you save it?

**Comment by JSettler** [comment]
Now i saved a new game within Build-1.4, quitted game and then restarted and tried to load that savegame: Error "Game could not be loaded" (with a blue disk symbol and a minus-sign shown below it). i had also a bug while building a road, it refused to build under/near broad-leaf trees.

**Comment by Pyrdacor** [comment]
Could you post the content of the log file please?

About the road building bug. Is this always happening near those trees or only sometimes?

**Comment by JSettler** [comment]
"Error: [savegame] Failed to load save game: [game]Invalid map size in file"
i used size 3 when starting the game (with 3 AI opponents, all 3 parameters maxed for all 4 players)

**Comment by JSettler** [comment]
(sorry for the delay, didnt know that you commented that fast)

**Comment by Pyrdacor** [comment]
Ok I will have a look at it tomorrow.

**Comment by JSettler** [comment]
[BUILD14GAME2.zip](https://github.com/Pyrdacor/freeserf.net/files/2950066/BUILD14GAME2.zip)

**Comment by Pyrdacor** [comment]
Maybe you can open the savegame with a text editor and look what value the map size has.

**Comment by JSettler** [comment]
the road-building bug happened near the blue castle in that savegame:
[BUILD14GAME1.zip](https://github.com/Pyrdacor/freeserf.net/files/2950070/BUILD14GAME1.zip)

ah ok

**Comment by JSettler** [comment]
the first lines of game2(build14):
[game 0]
  map.size = 3
  game_type = 0
  tick = 8118
  game_stats_counter = 882
  history_counter = 3882
...

**Comment by Pyrdacor** [comment]
Ok I found 3 bugs and fixed them. Could you please download v1.4 again and try it with the updated version? I updated the v1.4 build.

**Comment by Pyrdacor** [comment]
I was able to load your 2 savegames with the fixes.

**Comment by JSettler** [comment]
Yay, it works like a charm now!
Thank you very much!  :-)

Upto which mapsize is it reliable?

**Comment by JSettler** [comment]
ok now i found that road-building bug, it refuses to build a road north-west of the western flag which is directly left of the castle (maybe the tree "confuses" the road-algorithm?)
i tried to connect that flag to the northern hut
[B14B-M3-GAME1.zip](https://github.com/Pyrdacor/freeserf.net/files/2950130/B14B-M3-GAME1.zip)
should i open another issue/thread?

**Comment by Pyrdacor** [comment]
The map size is limited to 3 - 9.

**Comment by JSettler** [comment]
another minor issue was, that the sound for one event made a weird noise, i think it was the hammering sound of the construction worker, the sound was sometimes quite annoying but now i'm nearly used to it and try to ignore it; did you change something in the sound-server? (in jonls' version the sound was ok)

**Comment by Pyrdacor** [comment]
The sound engine is not quite perfect yet. I had to do it from scratch as the libraries that jonls used were not available for C# and also I tried to avoid dependencies as much as possible. Sound is on the ToDo list. ;-)

**Comment by Pyrdacor** [comment]
About the road bug. Yes please open another issue for it so I can close this one and can better track open issues.

**Comment by JSettler** [comment]
[ok done] did another save/load with the max mapsize(9), worked.
