### ISSUE TITLE
Builder and material not preset at new building

### ISSUE THREAD

**Issue by GORE84** [Pyrdacor/freeserf.net#80]
Started a new game and after making a Forest Ranger’s Hut nobody came with either material or a builder.

Attached savegame:
[BUG06.zip](https://github.com/Pyrdacor/freeserf.net/files/4174609/BUG06.zip)

**Comment by Pyrdacor** [comment]
This is no bug. The emergency program is active because you have very few planks and stone and the stonecutter is not built. Connect the road to the stonecutter. After the two planks are delivered to its construction site, the forester hut is continued.

**Comment by Pyrdacor** [comment]
But I noticed that the notifications are not shown anymore. That should have caused the confusion. I will fix the notifications. I opened a separate issue for this here: #81
